project:
  type: website
  output-dir: C:/Users/hphung.stu/OneDrive - UBC/Documents/GitHub/hieuphung

website:
  navbar:
    logo: site_logo/logo2.png
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - text: Remote Sensing
        menu:
          - href: final_project.qmd
            text: Detecting Change of AGB in Ghana
          - href: gem520_finallab.qmd
            text: Analysis of Burn Severity and Vegetation Recovery at Prouton Lake, BC
          - href: gem521_lab5.qmd
            text: Individual Trees Detecting using different methods
          - href: gem510_lab3.qmd
            text: Analysis of Suitable Sanctuaries for Humpback Whales
          - href: gem520_lab6.qmd
            text: Image Classification using R 
          - href: gem521_lab8.qmd
            text: Image Classification using eCognition
          - href: gem521_lab9.qmd
            text: Image Classification using Google Earth Engine
          - href: gem500_proposal.qmd
            text: Evaluating the Impact of Landsacape Fragmentation on Carbon Sequestration of Forests in Kwahu South, Ghana using Landscape Metrics and Landsat 8 Data
      - text: Environmental Projects
        menu:
          - href: thesis1.qmd
            text: Molten Salt Carbonate Electrolysis
          - href: thesis2.qmd
            text: Effect of Nanoparticles on TiO2
          - href: water_and_wastewater.qmd
            text: Design of Water, Wastewater, and Sludge Treatment
          - href: water_and_sewer.qmd
            text: Water and Sewer Network Design
      - text: Communication Skills and Indigenous Knowledge
        menu:
          - href: san_hoodia.qmd
          - text: The Hoodia Case Study. Disputed Rights, Shared Benefits, and Indigenous Epistemologies
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

