---
title: "Salmon Stream Network Analysis"
format: html
editor: visual
---

## Applied Skills

<div style="display: flex; flex-wrap: wrap; gap: 0.5rem; margin-bottom: 1.5rem;">

<span style="background-color: #1f3c73; color: white; padding: 0.5rem 1rem; border-radius: 0.5rem;">ArcGIS Pro</span>

<span style="background-color: #1f3c73; color: white; padding: 0.5rem 1rem; border-radius: 0.5rem;">Stream Network Analysis</span>

<span style="background-color: #1f3c73; color: white; padding: 0.5rem 1rem; border-radius: 0.5rem;">Tracing Stream Network</span>

</div>

::: panel-tabset
## Background

Least cost path analysis is a spatial modeling technique used to determine the most efficient route between two points across a landscape, taking into account varying levels of resistance or "cost" associated with different land cover types or terrain features. This method is widely applied in wildlife conservation to model animal movement and habitat connectivity, especially for species affected by habitat fragmentation. In the case of Grizzly Bears (Ursus arctos horribilis), which require large, contiguous territories for foraging and migration, understanding movement corridors is critical for effective management and protection efforts. Human development and landscape alteration in regions like the Rocky Mountain foothills of western Alberta have significantly constrained Grizzly Bear movement. By applying least cost path analysis, researchers can identify potential wildlife corridors that minimize conflict with human activity and support long-term species viability.

## Objectives

-   Gain hands-on experience with raster operations using GDAL both from the command line and in QGIS

-   Create and manipulate raster datasets from multiple sources

-   Perform raster calculations to derive new spatial data

-   Apply least cost path analysis to model wildlife movement

-   Explore habitat connectivity and conservation planning for Grizzly Bears in western Alberta using GIS tools

## Data descriptions

-   The data for this work was downloaded from UBC data source

## References

The instruction for the tasks was written by the teaching team of MGEM Program at The University of British Columbia

:::
