---
title: "Exploring the Art of Solutions and Design - Innovating at the crossroads of Forestry, Remote Sensing, and Environment"
page-layout: full

---
<!-- Full-width container -->
<div style="margin-left: -10vw; margin-right: -10vw; width: 100vw; position: relative; overflow: hidden;">

<video autoplay muted loop playsinline style="width: 120%; height: 600px; object-fit: cover;">
  <source src="videos/video1.mp4" type="video/mp4">
  Your browser does not support the video tag.
</video>

</div>



### Welcome to my e-portfolio 👋


My name is Hieu (pronounce as "Heal") Phung. You can call me Harry.

I am a fresh graduate student in Master of Geomatics for Environmental Management at The University of British Columbia.

Before coming to Canada, I have completed my Bachelor's in Energy and Environmental Engineering at Tampere University of Applied Sciences in Finland. I also completed one Master's programme in Environmental Engineering in Tampere University in Finland.

It is interesting that, after my first master's graduation, I decided to revolve my career path to the field of GIS and Forestry because I recognized an interconnection between environment, forestry and remote sensing field.

In my e-portfolio, I hope to deliver insights, creativity and innovations to readers.

Thank you and enjoy your time exploring my space. Should you have any questions, please do not hesitate to send me an email.

-   Skills: ArcGIS Pro, QGIS, R coding, Python, ENVI, eCognition, Google Earth Engine, AutoCAD, AutoCAD Plant 3D


<p style="text-align: center; margin-top: 30px;">
  <a href="contact.html" style="background-color: #4CAF50; color: white; padding: 12px 24px; text-decoration: none; font-size: 16px; border-radius: 8px;">
    Contact Me
  </a>
</p>

